version: 0.2

phases:
  pre_build:
    commands:
      - curl -qL -o packer.zip https://releases.hashicorp.com/packer/1.3.3/packer_1.3.3_linux_amd64.zip && unzip packer.zip
      - ./packer validate amazon-linux_packer-template.json
  build:
    commands:
      - ./delete_amis.sh
      - ./packer build amazon-linux_packer-template.json
  post_build:
    commands:
      - echo "done $(date)"
