version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - $(aws ecr get-login --no-include-email --region ${REGION})
      - cd data
      - aws s3 sync s3://${MODEL_BUCKET}/data/ ./
      - MODEL_FILE=$(ls -lt model_*.dat | head -n 1 | awk '{print $9}')
      - echo $MODEL_FILE
      - mv $MODEL_FILE model.dat
      - rm -f model_*.dat
      - ls -l
      - cd ..
  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Building the Docker image..."
      - docker build -t ${IMAGE_REPO_NAME}:${IMAGE_TAG} . -f Dockerfile_app
      - echo "docker tag ${IMAGE_REPO_NAME}:${IMAGE_TAG} ${ECR_REPO_URL}:${IMAGE_TAG}"
      - docker tag ${IMAGE_REPO_NAME}:${IMAGE_TAG} ${ECR_REPO_URL}:${IMAGE_TAG}
  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Pushing the Docker image..."
      - docker push ${ECR_REPO_URL}:${IMAGE_TAG}
      - touch dummy.zip

artifacts:
  files: dummy.zip
