FROM chainer/chainer:v5.1.0-python3

RUN apt-get update
RUN apt-get install -y nodejs npm curl
RUN npm install n -g
RUN n stable
RUN apt purge -y nodejs npm

# for serverless-python-requirements
RUN ln -s /usr/bin/python3.5 /usr/bin/python3.6
