service: ${env:SERVICE_NAME}

provider:
  name: aws
  runtime: python3.6
  region: ap-northeast-1
  stage: ${env:STAGE_ENV}
  role: ${env:LAMBDA_ROLE}
  environment:
    REGION: ${env:REGION}
    DYNAMO_PREFIX : ${env:DYNAMO_PREFIX}
  deploymentBucket:
    name: ${env:DEPLOY_BUCKET}

plugins:
  - serverless-python-requirements

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello