AWSTemplateFormatVersion: 2010-09-09
Description: App ECR Template
Resources:
  AppEcrRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: heta-reversi-app
  AppEcrBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
                - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      RoleName: heta-reversi-app-ecr-build
  AppEcrBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: heta-reversi-app-ecr
      ServiceRole: !Ref AppEcrBuildServiceRole
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/docker:18.09.0
        EnvironmentVariables:
          - Name: REGION
            Value: ap-northeast-1
            Type: PLAINTEXT
          - Name: IMAGE_REPO_NAME
            Value: heta-reversi-app
            Type: PLAINTEXT
          - Name: IMAGE_TAG
            Value: latest
            Type: PLAINTEXT
          - Name: ECR_REPO_URL
            Value: !Sub ${AWS::AccountId}.dkr.ecr.ap-northeast-1.amazonaws.com/heta-reversi-app
            Type: PLAINTEXT
          - Name: MODEL_BUCKET
            Value: test-batch-bucket-name
            Type: PLAINTEXT
      Source:
        Type: CODECOMMIT
        Location: https://git-codecommit.ap-northeast-1.amazonaws.com/v1/repos/heta-reversi
        BuildSpec: buildspec_app.yml
