AWSTemplateFormatVersion: 2010-09-09
Description: Model Create AWS Batch Template
Parameters:
  AMI:
    Type: String
Resources:
  ModelCreateEcrRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: heta-reversi-model-create
  ModelCreateEcrBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
                - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      RoleName: heta-reversi-model-create-ecr-build
  ModelCreateEcrBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: heta-reversi-model-create-ecr
      ServiceRole: !Ref ModelCreateEcrBuildServiceRole
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/docker:18.09.0
        EnvironmentVariables:
          - Name: REGION
            Value: ap-northeast-1
            Type: PLAINTEXT
          - Name: IMAGE_REPO_NAME
            Value: heta-reversi-model-create
            Type: PLAINTEXT
          - Name: IMAGE_TAG
            Value: latest
            Type: PLAINTEXT
          - Name: ECR_REPO_URL
            Value: !Sub ${AWS::AccountId}.dkr.ecr.ap-northeast-1.amazonaws.com/heta-reversi-model-create
            Type: PLAINTEXT
      Source:
        Type: CODECOMMIT
        Location: https://git-codecommit.ap-northeast-1.amazonaws.com/v1/repos/heta-reversi
        BuildSpec: buildspec_ecr.yml

  ModelCreateSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: heta-reversi-model-create-sg
      GroupDescription: heta-reversi-model-create-sg
      VpcId: !ImportValue heta-reversi-vpc-VPCID
